#!/bin/bash

exitflg=0

if type fontforge > /dev/null 2>&1; then
    echo '[CIVASEG]Fontforge is detected.'
else
    echo '[CIVASEG]Please install fontforge.(https://fontforge.github.io/en-US/)'
    exitflg=1
fi

if type woff2_compress > /dev/null 2>&1; then
    echo '[CIVASEG]Google woff2 is detected.'
else
    echo '[CIVASEG]Please install google woff2.(https://github.com/google/woff2)'
    exitflg=1
fi

if [ $exitflg -eq 1 ]; then
    exit 1
else
    for a in src/*.sfd; do
        fontfile=$(basename $a .sfd)
        namedir=$(echo $fontfile | sed "s,-.*,," | sed "s,Mini,-MINI,g;s,Modern,-Modern,;s,Classic,-Classic,;s,7SEGG,-7SEGG-,")
        name=$(echo $fontfile | sed "s,-.*,,")
        type=$(echo $fontfile | sed "s,.*-,,")
        mkdir -p fonts/${namedir}/
        fontforge -lang=ff -c 'Open($1); Generate($2)' src/${fontfile}.sfd fonts/$namedir/${name}-${type}.ttf >&/dev/null
        fontforge -lang=ff -c 'Open($1); Generate($2)' src/${fontfile}.sfd fonts/$namedir/${name}-${type}.woff >&/dev/null
        woff2_compress fonts/$namedir/${name}-${type}.ttf >&/dev/null
    done

    echo '[CIVASEG]CIVASEG font file is generated.'
fi
